---
# defaults file for c2-listener

client_user: cyrano
connect_host: target
connect_port: 8080
connect_message: "lab-checkin"
connect_timer_unit: "lab-checkin.timer"
connect_service_unit: "lab-checkin2.service"
connect_script_path: "/usr/local/bin/lab-checkin.sh"
connect_schedule: "*:0/10"
random_delay_seconds: 30