---
# This is a role for setting up the c2-server

- name: Add user and set password
  user:
    name: '{{ username }}'
    password: '{{ password | password_hash(''sha512'') }}'
    shell: '/bin/bash'
    groups: sudo
    append: yes

- name: Add host aliases
  lineinfile:
      path: '/etc/hosts'
      line: "{{ item.ip }} {{ item.name }}"
      state: present
  loop: "{{ hosts_entries }}"



