username: cyrano
password: cyrano
telnet_port: 2323
flag: "Top_Secret_Flag"
flag_2: "Cant_Guess_This"

hosts_entries:
    - { ip: "192.168.50.5", name: "target" }
    - { ip: "192.168.40.5", name: "c2-server" }
    - { ip: "192.168.50.6", name: "next-target" }
